name: Musicfun Deploy

permissions:
  id-token: write
  pages: write   # Добавьте, если настраиваете деплой на GitHub Pages
  contents: read # Обычно требуется для чтения кода репозитория

on:
  push:
    branches: [master]

jobs: 
  deploy: 
    runs-on: ubuntu-latest
    
    steps: 
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-versions: 20
      - run: npm install
      - run: npm run build
      - uses: actions/upload-pages-artifact@v3
        with:
          path: dist
      - uses: actions/deploy-pages@v4